"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PASSWORD_ENCRYPTION_UTILS_DECRYPTION_PARAMS = exports.PASSWORD_ENCRYPTION_UTILS_ENCRYPTION_PARAMS = exports.PASSWORD_ENCRYPTION_UTILS_ENCRYPTION_INITIALIZATION_VECTOR_LENGTH = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_IMPORT_FORMAT = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_EXPORT_FORMAT = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_USAGES = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_IS_EXPORTED = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_CONFIG = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_LENGTH = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_ALGORITHM = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BASE_KEY_CONFIG = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BITS_KEY_LENGTH_BYTES = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BITS_ITERATIONS = exports.PASSWORD_ENCRYPTION_UTILS_KEY_HASH_ALGORITHM = exports.PASSWORD_ENCRYPTION_UTILS_KEY_USAGES = exports.PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_IS_KEY_EXTRACTABLE = exports.PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_ALGORITHM = exports.PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_KEY_SALT_GENERATED_LENGTH = exports.PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_KEY_IMPORTED_FORMAT = void 0;
var const_1 = require("../const");
exports.PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_KEY_IMPORTED_FORMAT = 'raw';
exports.PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_KEY_SALT_GENERATED_LENGTH = 12;
exports.PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_ALGORITHM = 'PBKDF2';
exports.PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_IS_KEY_EXTRACTABLE = false;
exports.PASSWORD_ENCRYPTION_UTILS_KEY_USAGES = ['deriveBits', 'deriveKey'];
exports.PASSWORD_ENCRYPTION_UTILS_KEY_HASH_ALGORITHM = const_1.HASH_CALCULATION_UTILS_HASH_ALGORITHM.SHA256;
exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BITS_ITERATIONS = 100000;
exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BITS_KEY_LENGTH_BYTES = 16;
exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BASE_KEY_CONFIG = {
    name: exports.PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_ALGORITHM,
    hash: exports.PASSWORD_ENCRYPTION_UTILS_KEY_HASH_ALGORITHM,
    salt: null,
    iterations: exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BITS_ITERATIONS,
};
exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_ALGORITHM = 'AES-GCM';
exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_LENGTH = 128;
exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_CONFIG = {
    name: exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_ALGORITHM,
    length: exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_LENGTH,
};
exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_IS_EXPORTED = true;
exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_USAGES = [
    'encrypt',
    'decrypt',
];
exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_EXPORT_FORMAT = 'jwk';
exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_IMPORT_FORMAT = exports.PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_EXPORT_FORMAT;
exports.PASSWORD_ENCRYPTION_UTILS_ENCRYPTION_INITIALIZATION_VECTOR_LENGTH = 15;
exports.PASSWORD_ENCRYPTION_UTILS_ENCRYPTION_PARAMS = {
    name: 'AES-GCM',
    iv: null,
};
exports.PASSWORD_ENCRYPTION_UTILS_DECRYPTION_PARAMS = {
    name: 'AES-GCM',
    iv: null,
};
//# sourceMappingURL=password-utils.const.js.map