import { HASH_CALCULATION_UTILS_HASH_ALGORITHM } from '../const';
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_KEY_IMPORTED_FORMAT = "raw";
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_KEY_SALT_GENERATED_LENGTH = 12;
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_ALGORITHM = "PBKDF2";
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_IS_KEY_EXTRACTABLE = false;
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_USAGES: string[];
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_HASH_ALGORITHM = HASH_CALCULATION_UTILS_HASH_ALGORITHM.SHA256;
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BITS_ITERATIONS = 100000;
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BITS_KEY_LENGTH_BYTES = 16;
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BASE_KEY_CONFIG: {
    name: string;
    hash: HASH_CALCULATION_UTILS_HASH_ALGORITHM;
    salt: null;
    iterations: number;
};
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_ALGORITHM = "AES-GCM";
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_LENGTH = 128;
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_CONFIG: {
    name: string;
    length: number;
};
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_IS_EXPORTED = true;
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_USAGES: string[];
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_EXPORT_FORMAT = "jwk";
export declare const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_IMPORT_FORMAT = "jwk";
export declare const PASSWORD_ENCRYPTION_UTILS_ENCRYPTION_INITIALIZATION_VECTOR_LENGTH = 15;
export declare const PASSWORD_ENCRYPTION_UTILS_ENCRYPTION_PARAMS: {
    name: string;
    iv: null;
};
export declare const PASSWORD_ENCRYPTION_UTILS_DECRYPTION_PARAMS: {
    name: string;
    iv: null;
};
