"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SALT_GENERATION_UTILS_SALT_MAX_LENGTH_BYTES = exports.SALT_GENERATION_UTILS_SALT_MIN_LENGTH_BYTES = exports.SALT_GENERATION_UTILS_SALT_LENGTH_BYTES = void 0;
exports.SALT_GENERATION_UTILS_SALT_LENGTH_BYTES = 32;
exports.SALT_GENERATION_UTILS_SALT_MIN_LENGTH_BYTES = 4;
exports.SALT_GENERATION_UTILS_SALT_MAX_LENGTH_BYTES = 64;
//# sourceMappingURL=salt-utils.const.js.map