import {HASH_CALCULATION_UTILS_HASH_ALGORITHM} from '../const';

export const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_KEY_IMPORTED_FORMAT =
  'raw';

export const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_KEY_SALT_GENERATED_LENGTH = 12;

export const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_ALGORITHM = 'PBKDF2';

export const PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_IS_KEY_EXTRACTABLE =
  false;

export const PASSWORD_ENCRYPTION_UTILS_KEY_USAGES = ['deriveBits', 'deriveKey'];

export const PASSWORD_ENCRYPTION_UTILS_KEY_HASH_ALGORITHM =
  HASH_CALCULATION_UTILS_HASH_ALGORITHM.SHA256;

export const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BITS_ITERATIONS = 100000;

export const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BITS_KEY_LENGTH_BYTES = 16;

export const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BASE_KEY_CONFIG = {
  name: PASSWORD_ENCRYPTION_UTILS_KEY_GENERATION_ALGORITHM,
  hash: PASSWORD_ENCRYPTION_UTILS_KEY_HASH_ALGORITHM,
  salt: null,
  iterations: PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_BITS_ITERATIONS,
};

export const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_ALGORITHM =
  'AES-GCM';

export const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_LENGTH = 128;

export const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_CONFIG = {
  name: PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_ALGORITHM,
  length: PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_LENGTH,
};

export const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_IS_EXPORTED =
  true;

export const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_USAGES = [
  'encrypt',
  'decrypt',
];

export const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_EXPORT_FORMAT =
  'jwk';

export const PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_IMPORT_FORMAT =
  PASSWORD_ENCRYPTION_UTILS_KEY_DERIVED_TARGET_KEY_EXPORT_FORMAT;

export const PASSWORD_ENCRYPTION_UTILS_ENCRYPTION_INITIALIZATION_VECTOR_LENGTH = 15;

export const PASSWORD_ENCRYPTION_UTILS_ENCRYPTION_PARAMS = {
  name: 'AES-GCM',
  iv: null,
};

export const PASSWORD_ENCRYPTION_UTILS_DECRYPTION_PARAMS = {
  name: 'AES-GCM',
  iv: null,
};
