export enum HASH_CALCULATION_UTILS_HASH_ALGORITHM {
  SHA256 = 'SHA-256',
  SHA384 = 'SHA-384',
  SHA512 = 'SHA-512',
}

export const HASH_CALCULATION_UTILS_HASH_ALGORITHM_OUTPUT_STRING_LENGTH: {
  [key in HASH_CALCULATION_UTILS_HASH_ALGORITHM]: number;
} = {
  [HASH_CALCULATION_UTILS_HASH_ALGORITHM.SHA256]: 64,
  [HASH_CALCULATION_UTILS_HASH_ALGORITHM.SHA384]: 96,
  [HASH_CALCULATION_UTILS_HASH_ALGORITHM.SHA512]: 128,
};

export const HASH_CALCULATION_UTILS_DEFAULT_HASH_ALGORITHM =
  HASH_CALCULATION_UTILS_HASH_ALGORITHM.SHA256;

export enum CONST_CRYPTO_KEYS_TYPES {
  PUBLIC = 'public',
  PRIVATE = 'private',
}

export enum CONST_CRYPTO_KEYS_TYPES_EXPORT_FORMATS {
  RAW = 'raw',
  PKCS8 = 'pkcs8',
  SPKI = 'spki',
  JWK = 'jwk',
}
